import {defineConfig} from '@lingui/cli'

export default defineConfig({
  sourceLocale: 'en',
  runtimeConfigModule: {
    i18n: ['@lingui/core', 'i18n'],
    useLingui: ['@lingui/react', 'useLingui'],
    Trans: ['@lingui/react', 'Trans'],
  },
  macro: {
    corePackage: ['@lingui/macro', '@lingui/core/macro'],
    jsxPackage: ['@lingui/macro', '@lingui/react/macro'],
  },
  locales: [
    'en',
    'an',
    'ast',
    'ca',
    'cy',
    'da',
    'de',
    'el',
    'en-GB',
    'eo',
    'es',
    'eu',
    'fi',
    'fr',
    'fy',
    'ga',
    'gd',
    'gl',
    'hi',
    'hu',
    'ia',
    'id',
    'it',
    'ja',
    'km',
    'ko',
    'ne',
    'nl',
    'pl',
    'pt-BR',
    'pt-PT',
    'ro',
    'ru',
    'sv',
    'th',
    'tr',
    'uk',
    'vi',
    'zh-CN',
    'zh-HK',
    'zh-TW',
  ],
  catalogs: [
    {
      path: '<rootDir>/src/locale/locales/{locale}/messages',
      include: ['src'],
    },
  ],
  compileNamespace: 'ts',
})
