import { StyleSheet } from 'react-native'
import { tokens } from '../../theme'

export const consoleStyles = StyleSheet.create({
  stack: {
    gap: 14,
  },
  heroCard: {
    borderRadius: 18,
    padding: 18,
    backgroundColor: tokens.accentTransparent,
    borderWidth: 1,
    borderColor: tokens.accentBorder,
    gap: 6,
  },
  topStatus: {
    gap: 12,
  },
  appMark: {
    color: tokens.accent,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  screenTitle: {
    color: tokens.text,
    fontSize: 28,
    lineHeight: 33,
    fontWeight: '800',
  },
  screenSubtle: {
    color: tokens.muted,
    fontSize: 13,
    marginTop: 2,
  },
  statusPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statusPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: '800',
  },
  fullButton: {
    marginTop: 10,
    minHeight: 46,
  },
  metricRow: {
    flexDirection: 'row',
    gap: 10,
  },
  metric: {
    flex: 1,
    borderRadius: 14,
    padding: 12,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.glassBorder,
  },
  metricLabel: {
    color: tokens.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  metricValue: {
    color: tokens.text,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 3,
  },
  listBlock: {
    gap: 8,
  },
  sectionTitle: {
    color: tokens.text,
    fontSize: 17,
    fontWeight: '800',
  },
  sectionBody: {
    color: tokens.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  input: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: tokens.stroke,
    backgroundColor: tokens.surfaceRaised,
    color: tokens.text,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 16,
    marginTop: 8,
  },
  personaCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.glassBorder,
    gap: 8,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: tokens.surfaceRaised,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: tokens.text,
    fontSize: 18,
    fontWeight: '800',
  },
  cardTitle: {
    color: tokens.text,
    fontSize: 16,
    fontWeight: '800',
  },
  cardMeta: {
    color: tokens.accentSoft,
    fontSize: 12,
    fontWeight: '700',
  },
  cardBodyText: {
    color: tokens.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  surfaceStateRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
  },
  surfaceState: {
    flex: 1,
    borderRadius: 12,
    padding: 8,
    backgroundColor: tokens.surfaceTransparent,
  },
  surfaceStateLabel: {
    color: tokens.muted,
    fontSize: 10,
    fontWeight: '700',
  },
  surfaceStateValue: {
    color: tokens.text,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 2,
  },
  surfaceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 16,
    padding: 13,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.glassBorder,
  },
  surfaceIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptCard: {
    borderRadius: 16,
    padding: 14,
    gap: 8,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.glassBorder,
  },
  notificationCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    borderRadius: 16,
    padding: 13,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.glassBorder,
  },
  rowTitle: {
    color: tokens.text,
    fontSize: 14,
    fontWeight: '800',
  },
  rowDetail: {
    color: tokens.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  rowMeta: {
    color: tokens.accentSoft,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'right',
    maxWidth: 92,
  },
  textButton: {
    paddingVertical: 4,
  },
  textButtonLabel: {
    color: tokens.accentSoft,
    fontSize: 12,
    fontWeight: '800',
  },
  claimRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  claimChip: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    backgroundColor: tokens.surfaceTransparent,
    borderWidth: 1,
    borderColor: tokens.glassBorder,
  },
  claimText: {
    color: tokens.accentSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  factRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  factLabel: {
    color: tokens.muted,
    fontSize: 12,
  },
  factValue: {
    color: tokens.text,
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
  },
  emptyCard: {
    alignItems: 'center',
    borderRadius: 16,
    padding: 18,
    gap: 8,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.glassBorder,
  },
  disabled: {
    opacity: 0.5,
  },
  progressRail: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  progressStep: {
    flex: 1,
    gap: 6,
    alignItems: 'center',
  },
  progressDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: tokens.surfaceRaised,
    borderWidth: 1,
    borderColor: tokens.stroke,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressDotDone: {
    backgroundColor: tokens.accent,
    borderColor: tokens.accent,
  },
  progressLabel: {
    color: tokens.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  progressLabelDone: {
    color: tokens.text,
  },
})
