services:
  web:
    image: fatfingers23/moover_web:latest
    #    build:
    #      context: .
    #      dockerfile: ./Dockerfiles/web.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - moover-network
    env_file:
      - path: .env
        required: true
    environment:
      - VITE_DIST=/app/vite/dist
      - PUBLIC_ASSETS=/app/public
    depends_on:
      - postgres
  web-ui:
    #    image: fatfingers23/moover_web_ui:latest
    build:
      context: .
      dockerfile: ./Dockerfiles/web-ui.Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - path: .env
        required: false
    environment:
      - PORT=3001
    networks:
      - moover-network
  cron-worker:
    image: fatfingers23/moover_cron_worker:latest
    #    build:
    #      context: .
    #      dockerfile: ./Dockerfiles/cron-worker.Dockerfile
    networks:
      - moover-network
    env_file:
      - path: .env
        required: true
    depends_on:
      - postgres
  worker:
    image: fatfingers23/moover_worker:latest
    #    build:
    #      context: .
    #      dockerfile: ./Dockerfiles/worker.Dockerfile
    networks:
      - moover-network
    env_file:
      - path: .env
        required: true
    environment:
      - WORKER_NODE_NAME=rogue-one
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - moover-postgres-data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - moover-network
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - moover-network
    volumes:
      - 'moover_bucket_store:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
volumes:
  moover-postgres-data:
  moover_bucket_store:
networks:
  moover-network:
    driver: bridge

