import {NINTHS_COMMUNITIES} from '#/lib/communities'
import {type Highlight} from './types'

export const AVATAR_URLS = [
  'https://i.pravatar.cc/150?img=1',
  'https://i.pravatar.cc/150?img=2',
  'https://i.pravatar.cc/150?img=3',
  'https://i.pravatar.cc/150?img=4',
  'https://i.pravatar.cc/150?img=5',
  'https://i.pravatar.cc/150?img=6',
  'https://i.pravatar.cc/150?img=7',
  'https://i.pravatar.cc/150?img=8',
  'https://i.pravatar.cc/150?img=9',
]

export const HIGHLIGHTS: Highlight[] = [
  // JALISCO (Mix)
  {
    id: 'jal_1',
    text: 'El transporte público debe ser gestionado por el estado para garantizar tarifas justas',
    postAuthor: '@movilidad_jal',
    authorName: 'Movilidad Jalisco',
    avatarUrl: AVATAR_URLS[0],
    postPreview:
      'La nueva línea 4 del tren ligero es un paso, pero necesitamos más control estatal...',
    color: NINTHS_COMMUNITIES.authLeft.color,
    community: NINTHS_COMMUNITIES.authLeft.name,
    state: 'Jalisco',
    party: 'Morena',
    createdAt: Date.now() - 3600000,
    upvotes: 342,
    downvotes: 0,
    saves: 89,
    replyCount: 15,
    isVerified: true,
    isTrending: true,
  },
  {
    id: 'jal_2',
    text: 'Guadalajara se consolida como el Silicon Valley de México gracias a la inversión privada',
    postAuthor: '@tech_gdl',
    authorName: 'Tech GDL',
    avatarUrl: AVATAR_URLS[1],
    postPreview:
      'Las startups tecnológicas están generando miles de empleos bien remunerados...',
    color: NINTHS_COMMUNITIES.centerRight.color,
    community: NINTHS_COMMUNITIES.centerRight.name,
    state: 'Jalisco',
    party: 'PRI',
    createdAt: Date.now() - 7200000,
    upvotes: 567,
    downvotes: 0,
    saves: 234,
    isVerified: true,
    isTrending: false,
  },
  {
    id: 'jal_3',
    text: 'Protejamos el Bosque de la Primavera de la especulación inmobiliaria',
    postAuthor: '@bosque_vivo',
    authorName: 'Bosque Vivo',
    avatarUrl: AVATAR_URLS[2],
    postPreview:
      'No más desarrollos habitacionales en áreas protegidas. El pulmón de la ciudad es sagrado...',
    color: NINTHS_COMMUNITIES.libLeft.color,
    community: NINTHS_COMMUNITIES.libLeft.name,
    state: 'Jalisco',
    party: 'PVEM',
    createdAt: Date.now() - 15000000,
    upvotes: 890,
    downvotes: 0,
    saves: 450,
    isVerified: false,
    isTrending: true,
  },
  {
    id: 'jal_4',
    text: 'La familia tradicional es el núcleo de nuestra sociedad tapatía',
    postAuthor: '@valores_jal',
    authorName: 'Valores Jalisco',
    avatarUrl: AVATAR_URLS[3],
    postPreview:
      'Debemos promover políticas que fortalezcan la unión familiar y los valores...',
    color: NINTHS_COMMUNITIES.authRight.color,
    community: NINTHS_COMMUNITIES.authRight.name,
    state: 'Jalisco',
    party: 'PAN',
    createdAt: Date.now() - 86400000,
    upvotes: 210,
    downvotes: 0,
    saves: 45,
    isVerified: false,
    isTrending: false,
  },

  // NUEVO LEÓN (Leaning Right/Industrial)
  {
    id: 'nl_1',
    text: 'Monterrey demuestra que el trabajo duro y la libre empresa son el camino',
    postAuthor: '@regio_empresa',
    authorName: 'Empresa Regia',
    avatarUrl: AVATAR_URLS[4],
    postPreview:
      'Somos el motor industrial de México y exigimos un trato fiscal justo...',
    color: NINTHS_COMMUNITIES.libRight.color,
    community: NINTHS_COMMUNITIES.libRight.name,
    state: 'Nuevo León',
    party: 'MC',
    createdAt: Date.now() - 4000000,
    upvotes: 750,
    downvotes: 0,
    saves: 120,
    isVerified: true,
    isTrending: true,
  },
  {
    id: 'nl_2',
    text: 'Seguridad total en nuestras fronteras y carreteras para proteger el comercio',
    postAuthor: '@seguridad_nl',
    authorName: 'Seguridad NL',
    avatarUrl: AVATAR_URLS[5],
    postPreview:
      'Sin seguridad no hay inversión. Necesitamos mano dura contra el crimen...',
    color: NINTHS_COMMUNITIES.authRight.color,
    community: NINTHS_COMMUNITIES.authRight.name,
    state: 'Nuevo León',
    party: 'PAN',
    createdAt: Date.now() - 9000000,
    upvotes: 430,
    downvotes: 0,
    saves: 80,
    isVerified: true,
    isTrending: false,
  },
  {
    id: 'nl_3',
    text: 'Innovación y criptomonedas: el futuro financiero de San Pedro',
    postAuthor: '@crypto_mty',
    authorName: 'Crypto MTY',
    avatarUrl: AVATAR_URLS[6],
    postPreview:
      'Debemos desregular el sector fintech para atraer más capital de riesgo...',
    color: NINTHS_COMMUNITIES.libCenter.color,
    community: NINTHS_COMMUNITIES.libCenter.name,
    state: 'Nuevo León',
    createdAt: Date.now() - 12000000,
    upvotes: 320,
    downvotes: 0,
    saves: 150,
    isVerified: false,
    isTrending: false,
  },
  {
    id: 'nl_4',
    text: 'El agua es un derecho humano, no una mercancía',
    postAuthor: '@agua_para_todos',
    authorName: 'Agua Para Todos',
    avatarUrl: AVATAR_URLS[7],
    postPreview:
      'La crisis hídrica en Monterrey no se resuelve privatizando, sino gestionando mejor...',
    color: NINTHS_COMMUNITIES.libLeft.color,
    community: NINTHS_COMMUNITIES.libLeft.name,
    state: 'Nuevo León',
    party: 'Morena',
    createdAt: Date.now() - 20000000,
    upvotes: 600,
    downvotes: 0,
    saves: 300,
    isVerified: false,
    isTrending: true,
  },

  // CIUDAD DE MÉXICO (Mix, Leaning Left)
  {
    id: 'cdmx_1',
    text: 'El transporte público subvencionado es vital para la movilidad social',
    postAuthor: '@metro_cdmx_user',
    authorName: 'Usuario Metro',
    avatarUrl: AVATAR_URLS[8],
    postPreview:
      '5 pesos es un precio justo. El estado debe garantizar movilidad accesible para todos...',
    color: NINTHS_COMMUNITIES.authLeft.color,
    community: NINTHS_COMMUNITIES.authLeft.name,
    state: 'Ciudad de México',
    party: 'Morena',
    createdAt: Date.now() - 2000000,
    upvotes: 1200,
    downvotes: 0,
    saves: 400,
    isVerified: true,
    isTrending: true,
  },
  {
    id: 'cdmx_2',
    text: 'Derechos plenos para la comunidad LGBTQ+ en toda la ciudad',
    postAuthor: '@diversidad_capital',
    authorName: 'Diversidad Capital',
    avatarUrl: AVATAR_URLS[0],
    postPreview:
      'CDMX es un refugio de libertad y debemos defender los derechos ganados...',
    color: NINTHS_COMMUNITIES.libLeft.color,
    community: NINTHS_COMMUNITIES.libLeft.name,
    state: 'Ciudad de México',
    party: 'PRD',
    createdAt: Date.now() - 5500000,
    upvotes: 980,
    downvotes: 0,
    saves: 350,
    isVerified: true,
    isTrending: true,
  },
  {
    id: 'cdmx_3',
    text: 'Regularización de rentas ya: la gentrificación nos expulsa',
    postAuthor: '@vivienda_justa',
    authorName: 'Vivienda Justa',
    avatarUrl: AVATAR_URLS[1],
    postPreview:
      'Necesitamos control de precios en las rentas de la Roma y Condesa...',
    color: NINTHS_COMMUNITIES.centerLeft.color,
    community: NINTHS_COMMUNITIES.centerLeft.name,
    state: 'Ciudad de México',
    party: 'PT',
    createdAt: Date.now() - 18000000,
    upvotes: 850,
    downvotes: 0,
    saves: 280,
    isVerified: false,
    isTrending: true,
  },
  {
    id: 'cdmx_4',
    text: 'Seguridad y orden en el Centro Histórico para el comercio',
    postAuthor: '@comerciantes_centro',
    authorName: 'Comerciantes Centro',
    avatarUrl: AVATAR_URLS[2],
    postPreview:
      'El comercio informal debe ser ordenado. Necesitamos estado de derecho...',
    color: NINTHS_COMMUNITIES.authCenter.color,
    community: NINTHS_COMMUNITIES.authCenter.name,
    state: 'Ciudad de México',
    party: 'PRI',
    createdAt: Date.now() - 25000000,
    upvotes: 340,
    downvotes: 0,
    saves: 60,
    isVerified: false,
    isTrending: false,
  },

  // BAJA CALIFORNIA (Border/Trade)
  {
    id: 'bc_1',
    text: 'Tijuana capital mundial del turismo médico',
    postAuthor: '@salud_frontera',
    authorName: 'Salud Frontera',
    avatarUrl: AVATAR_URLS[3],
    postPreview:
      'La inversión en hospitales privados atrae divisas y genera empleo de calidad...',
    color: NINTHS_COMMUNITIES.centerRight.color,
    community: NINTHS_COMMUNITIES.centerRight.name,
    state: 'Baja California',
    party: 'PAN',
    createdAt: Date.now() - 6000000,
    upvotes: 410,
    downvotes: 0,
    saves: 95,
    isVerified: true,
    isTrending: false,
  },
  {
    id: 'bc_2',
    text: 'Cultura fronteriza: un puente entre dos mundos',
    postAuthor: '@arte_tijuana',
    authorName: 'Arte Tijuana',
    avatarUrl: AVATAR_URLS[4],
    postPreview:
      'Nuestra identidad es híbrida y libre. Apoyemos a los artistas locales...',
    color: NINTHS_COMMUNITIES.libCenter.color,
    community: NINTHS_COMMUNITIES.libCenter.name,
    state: 'Baja California',
    createdAt: Date.now() - 14000000,
    upvotes: 280,
    downvotes: 0,
    saves: 110,
    isVerified: false,
    isTrending: false,
  },
  {
    id: 'bc_3',
    text: 'Control estricto en la frontera para ordenar la migración',
    postAuthor: '@frontera_segura',
    authorName: 'Frontera Segura',
    avatarUrl: AVATAR_URLS[5],
    postPreview:
      'La migración debe ser legal y ordenada por el bien de todos...',
    color: NINTHS_COMMUNITIES.authRight.color,
    community: NINTHS_COMMUNITIES.authRight.name,
    state: 'Baja California',
    party: 'PAN',
    createdAt: Date.now() - 28000000,
    upvotes: 550,
    downvotes: 0,
    saves: 130,
    isVerified: false,
    isTrending: true,
  },

  // VERACRUZ (Port/Agri)
  {
    id: 'ver_1',
    text: 'Apoyo total a los cañeros y cafetaleros del estado',
    postAuthor: '@campo_veracruz',
    authorName: 'Campo Veracruz',
    avatarUrl: AVATAR_URLS[6],
    postPreview:
      'Sin subsidios al campo no hay comida en la mesa. Soberanía alimentaria...',
    color: NINTHS_COMMUNITIES.authLeft.color,
    community: NINTHS_COMMUNITIES.authLeft.name,
    state: 'Veracruz',
    party: 'Morena',
    createdAt: Date.now() - 3500000,
    upvotes: 390,
    downvotes: 0,
    saves: 75,
    isVerified: true,
    isTrending: false,
  },
  {
    id: 'ver_2',
    text: 'El Carnaval es nuestra mayor tradición, hay que preservarlo',
    postAuthor: '@alegria_jarocha',
    authorName: 'Alegría Jarocha',
    avatarUrl: AVATAR_URLS[7],
    postPreview: 'Más allá de la fiesta, es nuestra identidad cultural...',
    color: NINTHS_COMMUNITIES.centrist.color,
    community: NINTHS_COMMUNITIES.centrist.name,
    state: 'Veracruz',
    createdAt: Date.now() - 11000000,
    upvotes: 620,
    downvotes: 0,
    saves: 200,
    isVerified: false,
    isTrending: true,
  },

  // YUCATÁN (Security/Tourism)
  {
    id: 'yuc_1',
    text: 'Mérida: la ciudad más segura de México gracias a la cooperación ciudadana',
    postAuthor: '@merida_segura',
    authorName: 'Mérida Segura',
    avatarUrl: AVATAR_URLS[8],
    postPreview:
      'Nuestra policía comunitaria es modelo nacional. El orden trae paz...',
    color: NINTHS_COMMUNITIES.authRight.color,
    community: NINTHS_COMMUNITIES.authRight.name,
    state: 'Yucatán',
    party: 'PAN',
    createdAt: Date.now() - 5000000,
    upvotes: 810,
    downvotes: 0,
    saves: 190,
    isVerified: true,
    isTrending: true,
  },
  {
    id: 'yuc_2',
    text: 'Inversión extranjera en energías renovables para la península',
    postAuthor: '@energia_maya',
    authorName: 'Energía Maya',
    avatarUrl: AVATAR_URLS[0],
    postPreview:
      'Aprovechemos el sol y el viento. Apertura a empresas globales...',
    color: NINTHS_COMMUNITIES.libRight.color,
    community: NINTHS_COMMUNITIES.libRight.name,
    state: 'Yucatán',
    party: 'MC',
    createdAt: Date.now() - 16000000,
    upvotes: 290,
    downvotes: 0,
    saves: 60,
    isVerified: false,
    isTrending: false,
  },

  // VARIOUS
  {
    id: 'var_1',
    text: 'Legalización de las drogas para acabar con la violencia',
    postAuthor: '@regulacion_ya',
    authorName: 'Regulación Ya',
    avatarUrl: AVATAR_URLS[1],
    postPreview:
      'La prohibición ha fallado. Necesitamos un enfoque de salud pública...',
    color: NINTHS_COMMUNITIES.libCenter.color,
    community: NINTHS_COMMUNITIES.libCenter.name,
    state: 'Ciudad de México',
    createdAt: Date.now() - 45000000,
    upvotes: 770,
    downvotes: 0,
    saves: 310,
    isVerified: true,
    isTrending: true,
  },
  {
    id: 'var_2',
    text: 'El futuro es feminista',
    postAuthor: '@marea_verde',
    authorName: 'Marea Verde',
    avatarUrl: AVATAR_URLS[2],
    postPreview:
      'El futuro es feminista o no será. Por nuestros derechos reproductivos y contra la violencia de género...',
    color: NINTHS_COMMUNITIES.libLeft.color,
    community: NINTHS_COMMUNITIES.libLeft.name,
    state: 'Ciudad de México',
    party: 'Morena',
    createdAt: Date.now() - 1000000,
    upvotes: 1500,
    downvotes: 0,
    saves: 600,
    replyCount: 42,
    isVerified: true,
    isTrending: true,
  },
]

// O(1) Lookup Map
export const HIGHLIGHTS_BY_ID: Record<string, Highlight> = Object.fromEntries(
  HIGHLIGHTS.map(h => [h.id, h]),
)

// Helpers
export function filterHighlightsByState(state: string): Highlight[] {
  return HIGHLIGHTS.filter(h => h.state === state)
}
