import {type Document, type Meme} from './types'

export const MEMES: Meme[] = [
  {
    id: 'm1',
    type: 'Meme',
    category: 'Humor',
    title: 'When the budget passes',
    votes: 1240,
    comments: 182,
    color: '#FFD700',
    author: '@meme_lord',
    community: 'Auth Left',
    state: 'Nuevo Leon',
    party: 'Morena',
  },
  {
    id: 'm2',
    type: 'Meme',
    category: 'Humor',
    title: 'The state of the roads',
    votes: 890,
    comments: 96,
    color: '#FF6347',
    author: '@citizenX',
    community: 'Center Right',
    state: 'Jalisco',
    party: 'PAN',
  },
  {
    id: 'm3',
    type: 'Meme',
    category: 'Campaign',
    title: 'Vote for Progress!',
    votes: 450,
    comments: 41,
    color: '#4682B4',
    author: '@party_official',
    community: 'Center Left',
    state: 'Ciudad de Mexico',
    party: 'MC',
  },
  {
    id: 'm4',
    type: 'Meme',
    category: 'Community',
    title: 'Waiting for the meeting to start',
    votes: 210,
    comments: 18,
    color: '#9ACD32',
    author: '@neighbor_joe',
    community: 'Lib Left',
    state: 'Oaxaca',
    party: 'PRI',
  },
  {
    id: 'm5',
    type: 'Meme',
    category: 'Humor',
    title: 'Budget committee starter pack',
    votes: 376,
    comments: 52,
    color: '#8B5CF6',
    author: '@floor_whip',
    community: 'Center Left',
    state: 'Puebla',
    party: 'PRD',
  },
  {
    id: 'm6',
    type: 'Meme',
    category: 'Campaign',
    title: 'When the rally playlist hits',
    votes: 541,
    comments: 67,
    color: '#14B8A6',
    author: '@plaza_norte',
    community: 'Lib Left',
    state: 'Veracruz',
    party: 'PT',
  },
  {
    id: 'm7',
    type: 'Meme',
    category: 'Humor',
    title: 'Polling day survival mode',
    votes: 688,
    comments: 109,
    color: '#F97316',
    author: '@casilla_memes',
    community: 'Center Right',
    state: 'Guanajuato',
    party: 'PAN',
  },
  {
    id: 'm8',
    type: 'Meme',
    category: 'Community',
    title: 'The group chat after the debate',
    votes: 298,
    comments: 34,
    color: '#EC4899',
    author: '@debate_watch',
    community: 'Auth Left',
    state: 'Chihuahua',
    party: 'Morena',
  },
]

export const DOCUMENTS: Document[] = [
  {
    id: 'd1',
    type: 'Doc',
    category: 'Official',
    title: 'Annual Transparency Report 2024',
    votes: 602,
    comments: 27,
    size: '2.4 MB',
    date: '2024-12-10',
    color: '#007AFF',
    community: 'Center Right',
    state: 'Nuevo Leon',
    party: 'PAN',
  },
  {
    id: 'd2',
    type: 'Doc',
    category: 'Policy Drafts',
    title: 'Urban Redevelopment Proposal',
    votes: 388,
    comments: 44,
    size: '5.1 MB',
    date: '2024-11-25',
    color: '#34C759',
    community: 'Auth Left',
    state: 'Ciudad de Mexico',
    party: 'Morena',
  },
  {
    id: 'd3',
    type: 'Doc',
    category: 'Official',
    title: 'Party Bylaws & Regulations',
    votes: 259,
    comments: 13,
    size: '1.2 MB',
    date: '2024-10-05',
    color: '#AF52DE',
    community: 'Lib Right',
    state: 'Jalisco',
    party: 'PRI',
  },
  {
    id: 'd4',
    type: 'Doc',
    category: 'Campaign',
    title: 'Electoral Platform Summary',
    votes: 491,
    comments: 35,
    size: '850 KB',
    date: '2024-12-15',
    color: '#FF9500',
    community: 'Center Left',
    state: 'Oaxaca',
    party: 'MC',
  },
  {
    id: 'd5',
    type: 'Doc',
    category: 'Official',
    title: 'Citizen Assembly Attendance Log',
    votes: 214,
    comments: 19,
    size: '740 KB',
    date: '2025-01-14',
    color: '#0EA5E9',
    community: 'Lib Left',
    state: 'Puebla',
    party: 'PT',
  },
  {
    id: 'd6',
    type: 'Doc',
    category: 'Policy Drafts',
    title: 'Metropolitan Mobility Plan',
    votes: 533,
    comments: 58,
    size: '3.8 MB',
    date: '2025-02-09',
    color: '#10B981',
    community: 'Center Left',
    state: 'Jalisco',
    party: 'MC',
  },
  {
    id: 'd7',
    type: 'Doc',
    category: 'Campaign',
    title: 'Regional Security Talking Points',
    votes: 329,
    comments: 23,
    size: '1.9 MB',
    date: '2025-01-30',
    color: '#F97316',
    community: 'Center Right',
    state: 'Nuevo Leon',
    party: 'PAN',
  },
  {
    id: 'd8',
    type: 'Doc',
    category: 'Official',
    title: 'Public Spending Tracker Overview',
    votes: 447,
    comments: 39,
    size: '2.1 MB',
    date: '2025-02-18',
    color: '#A855F7',
    community: 'Auth Left',
    state: 'Chiapas',
    party: 'Morena',
  },
]

export const MEMES_BY_ID: Record<string, Meme> = Object.fromEntries(
  MEMES.map(m => [m.id, m]),
)

export const DOCUMENTS_BY_ID: Record<string, Document> = Object.fromEntries(
  DOCUMENTS.map(d => [d.id, d]),
)
