import {type PolicyItem} from './types'

export const FEATURED_POLICIES: PolicyItem[] = [
  {
    id: 'p-feat-1',
    type: 'Policy',
    category: 'Economy',
    title: 'Universal Basic Income Pilot',
    promotedBy: 'Community',
    support: 85,
    color: '#FFD700',
    verified: true,
  },
  {
    id: 'p-feat-2',
    type: 'Policy',
    category: 'Economy',
    title: 'Green Energy Subsidy',
    promotedBy: 'Party',
    mentions: 3400,
    color: '#34C759',
    verified: true,
  },
  {
    id: 'p-feat-3',
    type: 'Policy',
    category: 'Public Services',
    title: 'National Digital Health Record System',
    promotedBy: 'Party',
    mentions: 2900,
    color: '#007AFF',
  },
]

export const COMMUNITY_POLICIES: PolicyItem[] = [
  {
    id: 'p-com-1',
    type: 'Policy',
    category: 'Economy',
    title: 'Free University Access',
    promotedBy: 'Community',
    community: 'Lib Left',
    support: 92,
    color: '#34C759',
    verified: true,
  },
  {
    id: 'p-com-2',
    type: 'Policy',
    category: 'Economy',
    title: 'Rent Control Initiative',
    promotedBy: 'Community',
    community: 'Center Left',
    support: 68,
    color: '#5AC8FA',
  },
  {
    id: 'p-com-3',
    type: 'Policy',
    category: 'Economy',
    title: 'Mexico City Clean Air Act',
    promotedBy: 'Community',
    community: 'CDMX',
    support: 88,
    color: '#AF52DE',
    verified: true,
  },
  {
    id: 'p-com-4',
    type: 'Policy',
    category: 'Transport',
    title: 'Bicycle Infrastructure Expansion',
    promotedBy: 'Community',
    community: 'Lib Left',
    support: 76,
    color: '#34C759',
  },
  {
    id: 'p-com-5',
    type: 'Policy',
    category: 'Public Services',
    title: 'Community Health Centers in Rural Areas',
    promotedBy: 'Community',
    community: 'Center Left',
    support: 83,
    color: '#FF2D55',
  },
  {
    id: 'p-com-6',
    type: 'Policy',
    category: 'Welfare',
    title: 'Universal Childcare Access',
    promotedBy: 'Community',
    community: 'Auth Left',
    support: 79,
    color: '#F93A3A',
    verified: true,
  },
]

export const PARTY_POLICIES: PolicyItem[] = [
  {
    id: 'p-morena-1',
    type: 'Policy',
    category: 'Welfare',
    title: 'Pensión para Adultos Mayores Boost',
    promotedBy: 'Party',
    party: 'Morena',
    mentions: 5200,
    color: '#610200',
    verified: true,
  },
  {
    id: 'p-pan-1',
    type: 'Policy',
    category: 'Economy',
    title: 'Small Business Tax Incentives',
    promotedBy: 'Party',
    party: 'PAN',
    mentions: 3100,
    color: '#004990',
    verified: true,
  },
  {
    id: 'p-pri-1',
    type: 'Policy',
    category: 'Transport',
    title: 'National Highway Expansion',
    promotedBy: 'Party',
    party: 'PRI',
    mentions: 2100,
    color: '#CE1126',
  },
  {
    id: 'p-mc-1',
    type: 'Policy',
    category: 'Public Services',
    title: 'Internet as a Universal Right',
    promotedBy: 'Party',
    party: 'MC',
    mentions: 4500,
    color: '#FF8300',
    verified: true,
  },
  {
    id: 'p-pt-1',
    type: 'Policy',
    category: 'Welfare',
    title: 'Workers Cooperative Tax Exemptions',
    promotedBy: 'Party',
    party: 'PT',
    mentions: 1200,
    color: '#CC0000',
  },
  {
    id: 'p-pvem-1',
    type: 'Policy',
    category: 'Economy',
    title: 'National Reforestation Program',
    promotedBy: 'Party',
    party: 'PVEM',
    mentions: 1800,
    color: '#00A651',
    verified: true,
  },
  {
    id: 'p-morena-2',
    type: 'Policy',
    category: 'Tax',
    title: 'Progressive Wealth Tax',
    promotedBy: 'Party',
    party: 'Morena',
    mentions: 3800,
    color: '#610200',
  },
]

export const STATE_POLICIES: PolicyItem[] = [
  {
    id: 'p-state-1',
    type: 'Policy',
    category: 'Public Services',
    title: 'Nuevo León Water Security Act',
    promotedBy: 'State',
    state: 'Nuevo León',
    support: 82,
    color: '#007AFF',
    verified: true,
  },
  {
    id: 'p-state-2',
    type: 'Policy',
    category: 'Law & Order',
    title: 'Jalisco Unified Police Force',
    promotedBy: 'State',
    state: 'Jalisco',
    support: 65,
    color: '#5856D6',
  },
  {
    id: 'p-state-3',
    type: 'Policy',
    category: 'Economy',
    title: 'CDMX Digital Literacy Program',
    promotedBy: 'State',
    state: 'Mexico City',
    support: 90,
    color: '#FF2D55',
    verified: true,
  },
  {
    id: 'p-state-4',
    type: 'Policy',
    category: 'Transport',
    title: 'Baja California Border Transit Reform',
    promotedBy: 'State',
    state: 'Baja California',
    support: 78,
    color: '#FF9500',
  },
  {
    id: 'p-state-5',
    type: 'Policy',
    category: 'Welfare',
    title: 'Chihuahua Indigenous Community Support Fund',
    promotedBy: 'State',
    state: 'Chihuahua',
    support: 74,
    color: '#AF52DE',
  },
]

export const RECOMMENDED_POLICIES: PolicyItem[] = [
  {
    id: 'p-rec-1',
    type: 'Policy',
    category: 'Welfare',
    title: 'Healthcare for All',
    promotedBy: 'Recommended',
    match: 95,
    color: '#FF2D55',
  },
  {
    id: 'p-rec-2',
    type: 'Policy',
    category: 'Economy',
    title: 'AI Regulation Framework',
    promotedBy: 'Recommended',
    match: 88,
    color: '#5AC8FA',
  },
  {
    id: 'p-rec-3',
    type: 'Policy',
    category: 'Foreign Policy',
    title: 'Latin American Trade Bloc Expansion',
    promotedBy: 'Recommended',
    match: 82,
    color: '#FFD700',
  },
]

// Consolidate for lookups by ID
const ALL_POLICIES = [
  ...FEATURED_POLICIES,
  ...COMMUNITY_POLICIES,
  ...PARTY_POLICIES,
  ...STATE_POLICIES,
  ...RECOMMENDED_POLICIES,
]

export const POLICIES_BY_ID: Record<string, PolicyItem> = Object.fromEntries(
  ALL_POLICIES.map(p => [p.id, p]),
)

// Helpers
export function filterPoliciesByState(state: string): PolicyItem[] {
  return STATE_POLICIES.filter(p => p.state === state)
}
