import {type RepresentativeItem} from './types'

export const REPRESENTATIVES: RepresentativeItem[] = [
  // FEDERAL EXECUTIVE
  {
    id: 'fed_exec_1',
    did: 'did:plc:para-official-federal-executive',
    name: 'Claudia Sheinbaum',
    handle: 'claudia-sheinbaum.test',
    category: 'President',
    affiliate: 'Morena',
    state: 'National',
    municipality: 'National',
    avatarColor: '#610200',
    type: 'Party',
    status: 'verified',
    followersCount: 4681950,
  },

  // NATIONAL PARTY DIRECTION ORGANS (INE)
  {
    id: 'party_pan_president_2026',
    name: 'Jorge Romero Herrera',
    handle: 'j-romero-pan.test',
    category: 'President',
    affiliate: 'PAN',
    state: 'National',
    municipality: 'National',
    avatarColor: '#004990',
    type: 'Party',
    followersCount: 2466956,
    description: 'Presidente nacional del Partido Acción Nacional.',
  },
  {
    id: 'party_pan_secretary_2026',
    name: 'Karen Michel González Márquez',
    handle: 'k-gonz-pan.test',
    category: 'Secretary',
    affiliate: 'PAN',
    state: 'National',
    municipality: 'National',
    avatarColor: '#004990',
    type: 'Party',
    followersCount: 56556,
    description: 'Secretaria nacional del Partido Acción Nacional.',
  },
  {
    id: 'party_pri_president_2026',
    name: 'Rafael Alejandro Moreno Cárdenas',
    handle: 'alito-pri.test',
    category: 'President',
    affiliate: 'PRI',
    state: 'National',
    municipality: 'National',
    avatarColor: '#CE1126',
    type: 'Party',
    followersCount: 3153556,
    description:
      'Presidente nacional del Partido Revolucionario Institucional.',
  },
  {
    id: 'party_pri_secretary_2026',
    name: 'Alma Carolina Viggiano Austria',
    handle: 'c-viggiano-pri.test',
    category: 'Secretary',
    affiliate: 'PRI',
    state: 'National',
    municipality: 'National',
    avatarColor: '#CE1126',
    type: 'Party',
    followersCount: 114196,
    description: 'Secretaria general del Partido Revolucionario Institucional.',
  },
  {
    id: 'party_pvem_executive_secretary_2026',
    name: 'Pilar Guerrero Rubio',
    handle: 'p-guerrero-pvem.test',
    category: 'Secretary',
    affiliate: 'PVEM',
    state: 'National',
    municipality: 'National',
    avatarColor: '#00A651',
    type: 'Party',
    followersCount: 108513,
    description: 'Secretaria ejecutiva del Partido Verde Ecologista de México.',
  },
  {
    id: 'party_pvem_technical_secretary_2026',
    name: 'Gabriela Aguilar García',
    handle: 'g-aguilar-pvem.test',
    category: 'Secretary',
    affiliate: 'PVEM',
    state: 'National',
    municipality: 'National',
    avatarColor: '#00A651',
    type: 'Party',
    followersCount: 86579,
    description: 'Secretaria técnica del Partido Verde Ecologista de México.',
  },
  {
    id: 'party_pt_coordinator_2026',
    name: 'Alberto Anaya Gutiérrez',
    handle: 'a-anaya-pt.test',
    category: 'Leader',
    affiliate: 'PT',
    state: 'National',
    municipality: 'National',
    avatarColor: '#D90000',
    type: 'Party',
    followersCount: 11717,
    description:
      'Integrante de la Comisión Coordinadora Nacional del Partido del Trabajo.',
  },
  {
    id: 'party_pt_technical_secretary_2026',
    name: 'Silvano Garay Ulloa',
    handle: 's-garay-pt.test',
    category: 'Secretary',
    affiliate: 'PT',
    state: 'National',
    municipality: 'National',
    avatarColor: '#D90000',
    type: 'Party',
    followersCount: 227392,
    description: 'Secretario técnico del Partido del Trabajo.',
  },
  {
    id: 'party_mc_coordinator_2026',
    name: 'Jorge Álvarez Máynez',
    handle: 'j-alvarez-mc.test',
    category: 'Leader',
    affiliate: 'MC',
    state: 'National',
    municipality: 'National',
    avatarColor: '#FF8300',
    type: 'Party',
    followersCount: 40741,
    description: 'Coordinador nacional de Movimiento Ciudadano.',
  },
  {
    id: 'party_morena_president_2026',
    name: 'Luisa María Alcalde Luján',
    handle: 'l-alcalde-morena.test',
    category: 'President',
    affiliate: 'Morena',
    state: 'National',
    municipality: 'National',
    avatarColor: '#610200',
    type: 'Party',
    followersCount: 2364647,
    description: 'Presidenta nacional de Morena registrada por el INE.',
  },
  {
    id: 'party_morena_secretary_2026',
    name: 'Carolina Rangel Gracida',
    handle: 'c-rangel-morena.test',
    category: 'Secretary',
    affiliate: 'Morena',
    state: 'National',
    municipality: 'National',
    avatarColor: '#610200',
    type: 'Party',
    followersCount: 204794,
    description: 'Secretaria general de Morena registrada por el INE.',
  },

  // GOVERNORS
  {
    id: 'gov_jal_1',
    name: 'Pablo Lemus',
    handle: 'pablo-lemus.test',
    category: 'Governor',
    affiliate: 'MC',
    state: 'Jalisco',
    municipality: 'State',
    avatarColor: '#FF8300',
    type: 'Party',
    followersCount: 1384834,
  },
  {
    id: 'gov_nl_1',
    did: 'did:plc:para-official-nuevo-leon-governor',
    name: 'Samuel García',
    handle: 'samuel-garcia.test',
    category: 'Governor',
    affiliate: 'MC',
    state: 'Nuevo León',
    municipality: 'State',
    avatarColor: '#FF8300',
    type: 'Party',
    status: 'verified',
    followersCount: 566653,
  },
  {
    id: 'gov_cdmx_1',
    name: 'Clara Brugada',
    handle: 'clara-brugada.test',
    category: 'Governor',
    affiliate: 'Morena',
    state: 'Ciudad de México',
    municipality: 'State',
    avatarColor: '#610200',
    type: 'Party',
    followersCount: 562489,
  },
  {
    id: 'gov_ver_1',
    name: 'Rocío Nahle',
    handle: 'rocio-nahle.test',
    category: 'Governor',
    affiliate: 'Morena',
    state: 'Veracruz',
    municipality: 'State',
    avatarColor: '#610200',
    type: 'Party',
    followersCount: 696493,
  },
  {
    id: 'gov_yuc_1',
    name: 'Huacho Díaz',
    handle: 'huacho-diaz.test',
    category: 'Governor',
    affiliate: 'Morena',
    state: 'Yucatán',
    municipality: 'State',
    avatarColor: '#610200',
    type: 'Party',
    followersCount: 958517,
  },
  {
    id: 'gov_bc_1',
    name: 'Marina del Pilar',
    handle: 'marina-delpilar.test',
    category: 'Governor',
    affiliate: 'Morena',
    state: 'Baja California',
    municipality: 'State',
    avatarColor: '#610200',
    type: 'Party',
    followersCount: 987925,
  },
  {
    id: 'gov_chi_1',
    name: 'Maru Campos',
    handle: 'maru-campos.test',
    category: 'Governor',
    affiliate: 'PAN',
    state: 'Chihuahua',
    municipality: 'State',
    avatarColor: '#004990',
    type: 'Party',
    followersCount: 1559806,
  },
  {
    id: 'gov_que_1',
    name: 'Mauricio Kuri',
    handle: 'mauricio-kuri.test',
    category: 'Governor',
    affiliate: 'PAN',
    state: 'Querétaro',
    municipality: 'State',
    avatarColor: '#004990',
    type: 'Party',
    followersCount: 1762524,
  },
  {
    id: 'gov_coa_1',
    name: 'Manolo Jiménez',
    handle: 'manolo-jimenez.test',
    category: 'Governor',
    affiliate: 'PRI',
    state: 'Coahuila',
    municipality: 'State',
    avatarColor: '#CE1126',
    type: 'Party',
    followersCount: 555649,
  },

  // SENATORS
  {
    id: 'sen_1',
    name: 'Adán Augusto López',
    handle: 'adan-augusto.test',
    category: 'Senator',
    affiliate: 'Morena',
    state: 'National',
    municipality: 'National',
    avatarColor: '#610200',
    type: 'Party',
    followersCount: 788508,
  },
  {
    id: 'sen_2',
    name: 'Gerardo Fernández Noroña',
    handle: 'gfnorona.test',
    category: 'Senator',
    affiliate: 'PT',
    state: 'National',
    municipality: 'National',
    avatarColor: '#D90000',
    type: 'Party',
    followersCount: 408496,
  },
  {
    id: 'sen_3',
    name: 'Alejandro Moreno',
    handle: 'alito-moreno.test',
    category: 'Senator',
    affiliate: 'PRI',
    state: 'National',
    municipality: 'National',
    avatarColor: '#CE1126',
    type: 'Party',
    followersCount: 771412,
  },
  {
    id: 'sen_4',
    name: 'Marko Cortés',
    handle: 'marko-cortes.test',
    category: 'Senator',
    affiliate: 'PAN',
    state: 'National',
    municipality: 'National',
    avatarColor: '#004990',
    type: 'Party',
    followersCount: 639898,
  },
  {
    id: 'sen_5',
    name: 'Luis Donaldo Colosio',
    handle: 'ld-colosio.test',
    category: 'Senator',
    affiliate: 'MC',
    state: 'Nuevo León',
    municipality: 'State',
    avatarColor: '#FF8300',
    type: 'Party',
    followersCount: 431148,
  },
  {
    id: 'sen_6',
    name: 'Lilly Téllez',
    handle: 'lilly-tellez.test',
    category: 'Senator',
    affiliate: 'PAN',
    state: 'Sonora',
    municipality: 'State',
    avatarColor: '#004990',
    type: 'Party',
    followersCount: 671029,
  },

  // DEPUTIES (Federal)
  {
    id: 'dep_1',
    name: 'Ricardo Monreal',
    handle: 'ricardo-monreal.test',
    category: 'Federal Deputy',
    affiliate: 'Morena',
    state: 'National',
    municipality: 'National',
    avatarColor: '#610200',
    type: 'Party',
    followersCount: 408944,
  },
  {
    id: 'dep_2',
    name: 'Jorge Romero',
    handle: 'jorge-romero.test',
    category: 'Federal Deputy',
    affiliate: 'PAN',
    state: 'Ciudad de México',
    municipality: 'Benito Juárez',
    avatarColor: '#004990',
    type: 'Party',
    followersCount: 245852,
  },
  {
    id: 'dep_3',
    name: 'Ivonne Ortega',
    handle: 'ivonne-ortega.test',
    category: 'Federal Deputy',
    affiliate: 'MC',
    state: 'Yucatán',
    municipality: 'State',
    avatarColor: '#FF8300',
    type: 'Party',
    followersCount: 103407,
  },

  // LOCAL / MAYORS
  {
    id: 'mun_gdl_1',
    name: 'Verónica Delgadillo',
    handle: 'veronica-del.test',
    category: 'City Council', // Mayor
    affiliate: 'MC',
    state: 'Jalisco',
    municipality: 'Guadalajara',
    avatarColor: '#FF8300',
    type: 'Party',
  },
  {
    id: 'mun_mty_1',
    name: 'Adrián de la Garza',
    handle: 'adrian-delagarza.test',
    category: 'City Council', // Mayor
    affiliate: 'PRI',
    state: 'Nuevo León',
    municipality: 'Monterrey',
    avatarColor: '#CE1126',
    type: 'Party',
  },
  {
    id: 'mun_mid_1',
    name: 'Cecilia Patrón',
    handle: 'cecilia-patron.test',
    category: 'City Council', // Mayor
    affiliate: 'PAN',
    state: 'Yucatán',
    municipality: 'Mérida',
    avatarColor: '#004990',
    type: 'Party',
  },
  {
    id: 'mun_zap_1',
    name: 'Juan José Frangie',
    handle: 'jj-frangie.test',
    category: 'City Council', // Mayor
    affiliate: 'MC',
    state: 'Jalisco',
    municipality: 'Zapopan',
    avatarColor: '#FF8300',
    type: 'Party',
  },

  // COMMUNITY LEADERS
  {
    id: 'com_1',
    name: 'Vecinos Unidos GDL',
    handle: 'vecinos-gdl.test',
    category: 'Local Leader',
    affiliate: 'Community',
    state: 'Jalisco',
    municipality: 'Guadalajara',
    avatarColor: '#34C759',
    type: 'Community',
    followersCount: 15463,
  },
  {
    id: 'com_2',
    name: 'Red Ciclista CDMX',
    handle: 'red-ciclista.test',
    category: 'Activist',
    affiliate: 'Mobility',
    state: 'Ciudad de México',
    municipality: 'State',
    avatarColor: '#5AC8FA',
    type: 'Community',
    followersCount: 65392,
  },
  {
    id: 'com_3',
    name: 'Defensores del Agua NL',
    handle: 'agua-nl.test',
    category: 'Activist',
    affiliate: 'Environment',
    state: 'Nuevo León',
    municipality: 'Monterrey',
    avatarColor: '#007AFF',
    type: 'Community',
    followersCount: 54597,
  },

  // DIGITAL REPRESENTATIVES (The 9 Quadrants)
  {
    id: 'dig_al_1',
    name: 'Comandante Rojo',
    handle: 'red-leader.test',
    category: 'Leader',
    affiliate: 'Auth Left',
    state: 'Digital',
    municipality: 'Global',
    avatarColor: '#F93A3A',
    type: 'Community',
    followersCount: 23210,
  },
  {
    id: 'dig_ll_1',
    name: 'Eco Warrior',
    handle: 'green-spox.test',
    category: 'Spokesperson',
    affiliate: 'Lib Left',
    state: 'Digital',
    municipality: 'Global',
    avatarColor: '#34C759',
    type: 'Community',
    followersCount: 50379,
  },
  {
    id: 'dig_lr_1',
    name: 'Crypto King',
    handle: 'lib-treasurer.test',
    category: 'Treasurer',
    affiliate: 'Lib Right',
    state: 'Digital',
    municipality: 'Global',
    avatarColor: '#AF52DE',
    type: 'Community',
    followersCount: 58221,
  },
  {
    id: 'dig_ar_1',
    name: 'Tradition Keeper',
    handle: 'auth-right-leader.test',
    category: 'Leader',
    affiliate: 'Auth Right',
    state: 'Digital',
    municipality: 'Global',
    avatarColor: '#5856D6',
    type: 'Community',
    followersCount: 27059,
  },
  {
    id: 'dig_cl_1',
    name: 'Union Voice',
    handle: 'center-left-spox.test',
    category: 'Spokesperson',
    affiliate: 'Center Left',
    state: 'Digital',
    municipality: 'Global',
    avatarColor: '#5AC8FA',
    type: 'Community',
    followersCount: 43396,
  },
  {
    id: 'dig_cr_1',
    name: 'Market Analyst',
    handle: 'center-right-treasurer.test',
    category: 'Treasurer',
    affiliate: 'Center Right',
    state: 'Digital',
    municipality: 'Global',
    avatarColor: '#007AFF',
    type: 'Community',
    followersCount: 42156,
  },
  {
    id: 'dig_lc_1',
    name: 'Free Spirit',
    handle: 'lib-center-leader.test',
    category: 'Leader',
    affiliate: 'Lib Center',
    state: 'Digital',
    municipality: 'Global',
    avatarColor: '#FF80FF',
    type: 'Community',
    followersCount: 29898,
  },
  {
    id: 'dig_ae_1',
    name: 'State Planner',
    handle: 'auth-econo-spox.test',
    category: 'Spokesperson',
    affiliate: 'Auth Econocenter',
    state: 'Digital',
    municipality: 'Global',
    avatarColor: '#FF3B30',
    type: 'Community',
    followersCount: 42676,
  },
  {
    id: 'dig_le_1',
    name: 'Tech Innovator',
    handle: 'lib-econo-treasurer.test',
    category: 'Treasurer',
    affiliate: 'Lib Econocenter',
    state: 'Digital',
    municipality: 'Global',
    avatarColor: '#30B0C7',
    type: 'Community',
    followersCount: 77052,
  },
  {
    id: 'fed_exec_2',
    name: 'Carla',
    handle: 'carla.test',
    category: 'Citizen',
    affiliate: 'Morena',
    state: 'National',
    municipality: 'National',
    avatarColor: '#610200',
    type: 'Party',
    followersCount: 27541,
  },
  {
    id: 'seed_alice_1',
    name: 'Alice Test',
    handle: 'alice.test',
    category: 'Citizen',
    affiliate: 'Morena',
    state: 'National',
    municipality: 'National',
    avatarColor: '#610200',
    type: 'Party',
    followersCount: 44565,
  },
  {
    id: 'seed_bob_1',
    name: 'Bob Test',
    handle: 'bob.test',
    category: 'Citizen',
    affiliate: 'PAN',
    state: 'National',
    municipality: 'National',
    avatarColor: '#004990',
    type: 'Party',
    followersCount: 22335,
  },
]

// O(1) Lookup Map
export const REPS_BY_ID: Record<string, RepresentativeItem> =
  Object.fromEntries(REPRESENTATIVES.map(r => [r.id, r]))

// Helpers
export function filterRepsByState(state: string): RepresentativeItem[] {
  return REPRESENTATIVES.filter(r => r.state === state)
}
