// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.pdsmoover.backup.describeServer
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct DescribeServerOutput<'a> {
    pub estimated_blobs_size_on_disk: i64,
    pub estimated_repos_size_on_disk: i64,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub last_backup_at: std::option::Option<jacquard_common::types::string::Datetime>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub next_backup_due_at: std::option::Option<
        jacquard_common::types::string::Datetime,
    >,
    /// Some status are cached for a while to save on resources. This is the last time the status was updated.
    pub status_last_updated: jacquard_common::types::string::Datetime,
    pub total_blobs: i64,
    pub total_repos: i64,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum DescribeServerError<'a> {
    #[serde(rename = "RepoNotFound")]
    RepoNotFound(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for DescribeServerError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::RepoNotFound(msg) => {
                write!(f, "RepoNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// XRPC request marker type
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    serde::Serialize,
    serde::Deserialize,
    jacquard_derive::IntoStatic
)]
pub struct DescribeServer;
/// Response type for
///com.pdsmoover.backup.describeServer
pub struct DescribeServerResponse;
impl jacquard_common::xrpc::XrpcResp for DescribeServerResponse {
    const NSID: &'static str = "com.pdsmoover.backup.describeServer";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = DescribeServerOutput<'de>;
    type Err<'de> = DescribeServerError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for DescribeServer {
    const NSID: &'static str = "com.pdsmoover.backup.describeServer";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = DescribeServerResponse;
}

/// Endpoint type for
///com.pdsmoover.backup.describeServer
pub struct DescribeServerRequest;
impl jacquard_common::xrpc::XrpcEndpoint for DescribeServerRequest {
    const PATH: &'static str = "/xrpc/com.pdsmoover.backup.describeServer";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = DescribeServer;
    type Response = DescribeServerResponse;
}