// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.pdsmoover.backup.getRepoStatus
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetRepoStatus<'a> {
    #[serde(borrow)]
    pub did: jacquard_common::types::string::Did<'a>,
}

pub mod get_repo_status_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDid<S> {}
    impl<S: State> State for SetDid<S> {
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetRepoStatusBuilder<'a, S: get_repo_status_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> GetRepoStatus<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetRepoStatusBuilder<'a, get_repo_status_state::Empty> {
        GetRepoStatusBuilder::new()
    }
}

impl<'a> GetRepoStatusBuilder<'a, get_repo_status_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetRepoStatusBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None,),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetRepoStatusBuilder<'a, S>
where
    S: get_repo_status_state::State,
    S::Did: get_repo_status_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> GetRepoStatusBuilder<'a, get_repo_status_state::SetDid<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        GetRepoStatusBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetRepoStatusBuilder<'a, S>
where
    S: get_repo_status_state::State,
    S::Did: get_repo_status_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetRepoStatus<'a> {
        GetRepoStatus {
            did: self.__unsafe_private_named.0.unwrap(),
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetRepoStatusOutput<'a> {
    pub active: bool,
    /// Optional field, the total number of blobs in the repo backup.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub blob_count: std::option::Option<i64>,
    /// Date the backups were created.
    pub created_at: jacquard_common::types::string::Datetime,
    #[serde(borrow)]
    pub did: jacquard_common::types::string::Did<'a>,
    /// Optional field, the current estimated size of the repo backup in bytes.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub estimated_backup_size: std::option::Option<i64>,
    /// Date of the last backup.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub last_backup: std::option::Option<jacquard_common::types::string::Datetime>,
    /// Optional field, if set to zero no missing blobs were found. If set to a number greater than zero, the number of missing blobs found from a backup and getting 404 on getBlob..
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub missing_blob_count: std::option::Option<i64>,
    /// Optional field, the current rev of the repo backup. If empty there's not a backup
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub rev: std::option::Option<jacquard_common::types::string::Tid>,
    /// Optional field, the current PDS or PDS like source of the backup.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub source: std::option::Option<jacquard_common::CowStr<'a>>,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum GetRepoStatusError<'a> {
    #[serde(rename = "RepoNotFound")]
    RepoNotFound(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for GetRepoStatusError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::RepoNotFound(msg) => {
                write!(f, "RepoNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///com.pdsmoover.backup.getRepoStatus
pub struct GetRepoStatusResponse;
impl jacquard_common::xrpc::XrpcResp for GetRepoStatusResponse {
    const NSID: &'static str = "com.pdsmoover.backup.getRepoStatus";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetRepoStatusOutput<'de>;
    type Err<'de> = GetRepoStatusError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetRepoStatus<'a> {
    const NSID: &'static str = "com.pdsmoover.backup.getRepoStatus";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetRepoStatusResponse;
}

/// Endpoint type for
///com.pdsmoover.backup.getRepoStatus
pub struct GetRepoStatusRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetRepoStatusRequest {
    const PATH: &'static str = "/xrpc/com.pdsmoover.backup.getRepoStatus";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetRepoStatus<'de>;
    type Response = GetRepoStatusResponse;
}