// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.pdsmoover.backup.removeRepo
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum RemoveRepoError<'a> {
    #[serde(rename = "NotFound")]
    NotFound(std::option::Option<jacquard_common::CowStr<'a>>),
    #[serde(rename = "NotAuthorized")]
    NotAuthorized(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for RemoveRepoError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotAuthorized(msg) => {
                write!(f, "NotAuthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// XRPC request marker type
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    serde::Serialize,
    serde::Deserialize,
    jacquard_derive::IntoStatic
)]
pub struct RemoveRepo;
/// Response type for
///com.pdsmoover.backup.removeRepo
pub struct RemoveRepoResponse;
impl jacquard_common::xrpc::XrpcResp for RemoveRepoResponse {
    const NSID: &'static str = "com.pdsmoover.backup.removeRepo";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = RemoveRepoError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for RemoveRepo {
    const NSID: &'static str = "com.pdsmoover.backup.removeRepo";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RemoveRepoResponse;
}

/// Endpoint type for
///com.pdsmoover.backup.removeRepo
pub struct RemoveRepoRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RemoveRepoRequest {
    const PATH: &'static str = "/xrpc/com.pdsmoover.backup.removeRepo";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = RemoveRepo;
    type Response = RemoveRepoResponse;
}