// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.pdsmoover.backup.signUp
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum SignUpError<'a> {
    #[serde(rename = "AlreadyRegistered")]
    AlreadyRegistered(std::option::Option<jacquard_common::CowStr<'a>>),
    #[serde(rename = "NotAuthorized")]
    NotAuthorized(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for SignUpError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AlreadyRegistered(msg) => {
                write!(f, "AlreadyRegistered")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotAuthorized(msg) => {
                write!(f, "NotAuthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// XRPC request marker type
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    serde::Serialize,
    serde::Deserialize,
    jacquard_derive::IntoStatic
)]
pub struct SignUp;
/// Response type for
///com.pdsmoover.backup.signUp
pub struct SignUpResponse;
impl jacquard_common::xrpc::XrpcResp for SignUpResponse {
    const NSID: &'static str = "com.pdsmoover.backup.signUp";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = SignUpError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for SignUp {
    const NSID: &'static str = "com.pdsmoover.backup.signUp";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = SignUpResponse;
}

/// Endpoint type for
///com.pdsmoover.backup.signUp
pub struct SignUpRequest;
impl jacquard_common::xrpc::XrpcEndpoint for SignUpRequest {
    const PATH: &'static str = "/xrpc/com.pdsmoover.backup.signUp";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = SignUp;
    type Response = SignUpResponse;
}