/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.civic.castVote'

export { $nsid }

/** Cast or replace the viewer's direct vote for a cabildeo. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    cabildeo: l.string({ format: 'at-uri' }),
    selectedOption: l.integer({ minimum: 0 }),
  }),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    cid: l.string({ format: 'cid' }),
    commit: l.ref<Commit>((() => commit) as any),
  }),
  [
    'NotFound',
    'InvalidPhase',
    'DeadlineExpired',
    'InvalidOption',
    'CommunityMembershipRequired',
  ],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output

type Commit = {
  $type?: 'com.para.civic.castVote#commit'
  cid: l.CidString
  rev: string
}

export type { Commit }

const commit = l.typedObject<Commit>(
  $nsid,
  'commit',
  l.object({ cid: l.string({ format: 'cid' }), rev: l.string() }),
)

export { commit }
