import {Router} from '#/lib/routes/router'

export const router = new Router({
  Home: ['/', '/download'],
  Search: '/search',
  Feeds: '/feeds',
  PartyFeed: '/feeds/party/:partyId',
  Notifications: '/notifications',
  NotificationsActivityList: '/notifications/activity',
  LegacyNotificationSettings: '/notifications/settings',
  Settings: '/settings',
  Lists: '/lists',
  // moderation
  Moderation: '/moderation',
  ModerationModlists: '/moderation/modlists',
  ModerationMutedAccounts: '/moderation/muted-accounts',
  ModerationBlockedAccounts: '/moderation/blocked-accounts',
  ModerationInteractionSettings: '/moderation/interaction-settings',
  ModerationVerificationSettings: '/moderation/verification-settings',
  // profiles, threads, lists
  Profile: ['/profile/:name', '/profile/:name/rss'],
  ProfileFollowers: '/profile/:name/followers',
  ProfileFollows: '/profile/:name/follows',
  ProfileKnownFollowers: '/profile/:name/known-followers',
  ProfileSearch: '/profile/:name/search',
  ProfileList: '/profile/:name/lists/:rkey',
  PostThread: '/profile/:name/post/:rkey',
  PostLikedBy: '/profile/:name/post/:rkey/liked-by',
  PostRepostedBy: '/profile/:name/post/:rkey/reposted-by',
  PostHighlights: '/profile/:name/post/:rkey/highlights',
  PostQuotes: '/profile/:name/post/:rkey/quotes',
  ProfileFeed: '/profile/:name/feed/:rkey',
  ProfileFeedLikedBy: '/profile/:name/feed/:rkey/liked-by',
  ProfileLabelerLikedBy: '/profile/:name/labeler/liked-by',
  // debug
  Debug: '/sys/debug',
  DebugMod: '/sys/debug-mod',
  Log: '/sys/log',
  // settings
  LanguageSettings: '/settings/language',
  AppPasswords: '/settings/app-passwords',
  PreferencesFollowingFeed: '/settings/following-feed',
  PreferencesThreads: '/settings/threads',
  PreferencesExternalEmbeds: '/settings/external-embeds',
  AccessibilitySettings: '/settings/accessibility',
  AppearanceSettings: '/settings/appearance',
  SavedFeeds: '/settings/saved-feeds',
  AccountSettings: '/settings/account',
  ProfileVisibility: '/settings/profile-visibility',
  PrivacyAndSecuritySettings: '/settings/privacy-and-security',
  ActivityPrivacySettings: '/settings/privacy-and-security/activity',
  ContentAndMediaSettings: '/settings/content-and-media',
  InterestsSettings: '/settings/interests',
  FollowedElementsSettings: '/settings/followed-elements',
  AboutSettings: '/settings/about',
  AppIconSettings: '/settings/app-icon',
  NotificationSettings: '/settings/notifications',
  ReplyNotificationSettings: '/settings/notifications/replies',
  MentionNotificationSettings: '/settings/notifications/mentions',
  QuoteNotificationSettings: '/settings/notifications/quotes',
  LikeNotificationSettings: '/settings/notifications/likes',
  RepostNotificationSettings: '/settings/notifications/reposts',
  NewFollowerNotificationSettings: '/settings/notifications/new-followers',
  LikesOnRepostsNotificationSettings:
    '/settings/notifications/likes-on-reposts',
  RepostsOnRepostsNotificationSettings:
    '/settings/notifications/reposts-on-reposts',
  ActivityNotificationSettings: '/settings/notifications/activity',
  MiscellaneousNotificationSettings: '/settings/notifications/miscellaneous',
  // support
  Support: '/support',
  PrivacyPolicy: '/support/privacy',
  TermsOfService: '/support/tos',
  CommunityGuidelines: '/support/community-guidelines',
  CopyrightPolicy: '/support/copyright',
  // hashtags
  Hashtag: '/hashtag/:tag',
  FlairFeed: '/flair/:flairId',
  Topic: '/topic/:topic',
  // DMs
  Messages: '/messages',
  MessagesSettings: '/messages/settings',
  Representatives: '/representatives',
  MessagesInbox: '/messages/inbox',
  MessagesConversation: '/messages/:conversation',
  MessagesConversationSettings: '/messages/:conversation/settings',
  MessagesJoinRequests: '/messages/:conversation/requests',
  // Data
  Data: '/data',
  MyBase: '/my-base',
  MyAffiliations: '/my-affiliations',
  Communities: '/communities',
  CreateCommunity: '/communities/create',
  CabildeoList: '/communities/cabildeos',
  CabildeoDetail: '/communities/cabildeos/:cabildeoUri',
  Agora: '/agora',
  CommunityDirectory: '/community-directory',
  ProposalDetail: '/agora/proposals/:proposalUri',
  DelegateVote: '/communities/cabildeos/:cabildeoUri/delegate-vote',
  CreateCabildeo: '/communities/cabildeos/create',
  CreatePosition: '/communities/cabildeos/:cabildeoUri/positions/create',
  CommunityProfile: [
    '/communities/profile/:communityId',
    '/p/:communityId',
    '/g/:communityId',
  ],
  PoliciesDashboard: '/policies-dashboard',
  PolicyDetails: '/policy-details',
  Memes: '/memes',
  Documents: '/documents',
  DiscourseAnalysis: '/discourse-analysis',
  CreatePost: '/create-post',
  PoliticalAffiliation: '/settings/political-affiliation',
  SeeVotes: '/my-base/votes',
  SeeInfluence: '/my-base/influence',
  SeePosts: '/my-base/posts',
  // starter packs
  Start: '/start/:name/:rkey',
  StarterPackEdit: '/starter-pack/edit/:rkey',
  StarterPack: '/starter-pack/:name/:rkey',
  StarterPackShort: '/starter-pack-short/:code',
  StarterPackWizard: '/starter-pack/create',
  VideoFeed: '/video-feed',
  Bookmarks: '/saved',
  // contacts
  CommunitiesActiveIn: '/profile/:name/communities',
  FindContactsSettings: '/settings/find-contacts',
  FindContactsFlow: '/find-contacts',
  VSScreenV2: '/comparison',
  AgentChat: '/agent-chat/:agentId',
  CommunityAgentProfile: '/communities/agent/:agentId',
  RAQ: '/raq',
  RAQAssessment: '/raq/assessment',
  ProposedRAQList: '/raq/proposed',
  OpenQuestionsList: '/raq/open-questions',
  OpenQuestionThread: '/raq/open-questions/:id',
  AxesDiscoveryList: '/raq/axes-discovery',
  AxisDetail: '/raq/axes/:axisId',
  RAQResults: '/raq/results',
  CommunityRAQ: '/communities/:communityId/raq',
  CommunityVoters: '/communities/:communityId/voters',
  CommunityRoles: '/communities/:communityId/roles',
  Highlights: '/highlights',
  SeeHighlightDetails: '/highlights/:highlightId',
  DistrictProfile: '/districts/:districtId',
  Map: '/map',
  Compass: '/compass',
  CommunityCivicTree: ['/community-civic-tree', '/deliberation'],
  CivicTree: ['/civic-tree', '/mapa-civico'],
  CollectionDetail: [
    '/civic-tree/collections/:collectionId',
    '/mapa-civico/branches/:collectionId',
  ],
  MyCommunities: '/my-communities',
  MyRAQ: '/raq/my',
})
