// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.pdsmoover.admin.removePds
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct RemovePds<'a> {
    /// Hostname of the current the PDS
    #[serde(borrow)]
    pub hostname: jacquard_common::CowStr<'a>,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum RemovePdsError<'a> {
    #[serde(rename = "NotFound")]
    NotFound(std::option::Option<jacquard_common::CowStr<'a>>),
    #[serde(rename = "NotAuthorized")]
    NotAuthorized(std::option::Option<jacquard_common::CowStr<'a>>),
    #[serde(rename = "NotAValidPDS")]
    NotAValidPds(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for RemovePdsError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotAuthorized(msg) => {
                write!(f, "NotAuthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotAValidPds(msg) => {
                write!(f, "NotAValidPDS")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///com.pdsmoover.admin.removePds
pub struct RemovePdsResponse;
impl jacquard_common::xrpc::XrpcResp for RemovePdsResponse {
    const NSID: &'static str = "com.pdsmoover.admin.removePds";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = RemovePdsError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for RemovePds<'a> {
    const NSID: &'static str = "com.pdsmoover.admin.removePds";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RemovePdsResponse;
}

/// Endpoint type for
///com.pdsmoover.admin.removePds
pub struct RemovePdsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RemovePdsRequest {
    const PATH: &'static str = "/xrpc/com.pdsmoover.admin.removePds";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = RemovePds<'de>;
    type Response = RemovePdsResponse;
}