// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.pdsmoover.admin.removeRepo
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct RemoveRepo<'a> {
    /// The did of the repo to remove
    #[serde(borrow)]
    pub did: jacquard_common::types::string::Did<'a>,
}

pub mod remove_repo_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDid<S> {}
    impl<S: State> State for SetDid<S> {
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type
pub struct RemoveRepoBuilder<'a, S: remove_repo_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> RemoveRepo<'a> {
    /// Create a new builder for this type
    pub fn new() -> RemoveRepoBuilder<'a, remove_repo_state::Empty> {
        RemoveRepoBuilder::new()
    }
}

impl<'a> RemoveRepoBuilder<'a, remove_repo_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        RemoveRepoBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None,),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> RemoveRepoBuilder<'a, S>
where
    S: remove_repo_state::State,
    S::Did: remove_repo_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> RemoveRepoBuilder<'a, remove_repo_state::SetDid<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        RemoveRepoBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> RemoveRepoBuilder<'a, S>
where
    S: remove_repo_state::State,
    S::Did: remove_repo_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> RemoveRepo<'a> {
        RemoveRepo {
            did: self.__unsafe_private_named.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> RemoveRepo<'a> {
        RemoveRepo {
            did: self.__unsafe_private_named.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum RemoveRepoError<'a> {
    #[serde(rename = "NotFound")]
    NotFound(std::option::Option<jacquard_common::CowStr<'a>>),
    #[serde(rename = "NotAuthorized")]
    NotAuthorized(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for RemoveRepoError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotAuthorized(msg) => {
                write!(f, "NotAuthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///com.pdsmoover.admin.removeRepo
pub struct RemoveRepoResponse;
impl jacquard_common::xrpc::XrpcResp for RemoveRepoResponse {
    const NSID: &'static str = "com.pdsmoover.admin.removeRepo";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = RemoveRepoError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for RemoveRepo<'a> {
    const NSID: &'static str = "com.pdsmoover.admin.removeRepo";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RemoveRepoResponse;
}

/// Endpoint type for
///com.pdsmoover.admin.removeRepo
pub struct RemoveRepoRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RemoveRepoRequest {
    const PATH: &'static str = "/xrpc/com.pdsmoover.admin.removeRepo";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = RemoveRepo<'de>;
    type Response = RemoveRepoResponse;
}