// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.pdsmoover.admin.requestRepoBackup
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct RequestRepoBackup<'a> {
    /// did of the repo to back up
    #[serde(borrow)]
    pub did: jacquard_common::CowStr<'a>,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum RequestRepoBackupError<'a> {
    #[serde(rename = "NotFound")]
    NotFound(std::option::Option<jacquard_common::CowStr<'a>>),
    #[serde(rename = "NotAuthorized")]
    NotAuthorized(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for RequestRepoBackupError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotAuthorized(msg) => {
                write!(f, "NotAuthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///com.pdsmoover.admin.requestRepoBackup
pub struct RequestRepoBackupResponse;
impl jacquard_common::xrpc::XrpcResp for RequestRepoBackupResponse {
    const NSID: &'static str = "com.pdsmoover.admin.requestRepoBackup";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = RequestRepoBackupError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for RequestRepoBackup<'a> {
    const NSID: &'static str = "com.pdsmoover.admin.requestRepoBackup";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RequestRepoBackupResponse;
}

/// Endpoint type for
///com.pdsmoover.admin.requestRepoBackup
pub struct RequestRepoBackupRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RequestRepoBackupRequest {
    const PATH: &'static str = "/xrpc/com.pdsmoover.admin.requestRepoBackup";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = RequestRepoBackup<'de>;
    type Response = RequestRepoBackupResponse;
}