// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.pdsmoover.admin.requestInstanceBackup
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum RequestInstanceBackupError<'a> {
    #[serde(rename = "NotFound")]
    NotFound(std::option::Option<jacquard_common::CowStr<'a>>),
    #[serde(rename = "NotAuthorized")]
    NotAuthorized(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for RequestInstanceBackupError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotAuthorized(msg) => {
                write!(f, "NotAuthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// XRPC request marker type
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    serde::Serialize,
    serde::Deserialize,
    jacquard_derive::IntoStatic
)]
pub struct RequestInstanceBackup;
/// Response type for
///com.pdsmoover.admin.requestInstanceBackup
pub struct RequestInstanceBackupResponse;
impl jacquard_common::xrpc::XrpcResp for RequestInstanceBackupResponse {
    const NSID: &'static str = "com.pdsmoover.admin.requestInstanceBackup";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = RequestInstanceBackupError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for RequestInstanceBackup {
    const NSID: &'static str = "com.pdsmoover.admin.requestInstanceBackup";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RequestInstanceBackupResponse;
}

/// Endpoint type for
///com.pdsmoover.admin.requestInstanceBackup
pub struct RequestInstanceBackupRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RequestInstanceBackupRequest {
    const PATH: &'static str = "/xrpc/com.pdsmoover.admin.requestInstanceBackup";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = RequestInstanceBackup;
    type Response = RequestInstanceBackupResponse;
}