// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.pdsmoover.admin.requestBackup
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum RequestBackupError<'a> {
    #[serde(rename = "NotFound")]
    NotFound(std::option::Option<String>),
    #[serde(rename = "NotAuthorized")]
    NotAuthorized(std::option::Option<String>),
}

impl std::fmt::Display for RequestBackupError<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotFound(msg) => {
                write!(f, "NotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::NotAuthorized(msg) => {
                write!(f, "NotAuthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// XRPC request marker type
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    serde::Serialize,
    serde::Deserialize,
    jacquard_derive::IntoStatic
)]
pub struct RequestBackup;
///Response type for
///com.pdsmoover.admin.requestBackup
pub struct RequestBackupResponse;
impl jacquard_common::xrpc::XrpcResp for RequestBackupResponse {
    const NSID: &'static str = "com.pdsmoover.admin.requestBackup";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = RequestBackupError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for RequestBackup {
    const NSID: &'static str = "com.pdsmoover.admin.requestBackup";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RequestBackupResponse;
}

///Endpoint type for
///com.pdsmoover.admin.requestBackup
pub struct RequestBackupRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RequestBackupRequest {
    const PATH: &'static str = "/xrpc/com.pdsmoover.admin.requestBackup";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = RequestBackup;
    type Response = RequestBackupResponse;
}