services:
  worker-one:
    image: fatfingers23/moover_worker:latest
    network_mode: host
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    environment:
      - WORKER_NODE_NAME=node-one-worker-one
  worker-two:
    image: fatfingers23/moover_worker:latest
    network_mode: host
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    environment:
      - WORKER_NODE_NAME=node-one-worker-two
  worker-three:
    image: fatfingers23/moover_worker:latest
    network_mode: host
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    environment:
      - WORKER_NODE_NAME=node-one-worker-three