services:
  web:
    image: fatfingers23/moover_web:latest
    restart: unless-stopped
    network_mode: host
    ports:
      - "3000:3000"
    env_file:
      - path: .env
        required: true
    environment:
      - VITE_DIST=/app/vite/dist
      - PUBLIC_ASSETS=/app/public
  web-ui:
    image: fatfingers23/moover_ui:latest
    network_mode: host
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - PUBLIC_XRPC_BASE=pdsmoover.com
  caddy:
    image: caddy:2-alpine
    network_mode: host
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
      - web-ui
  #Only a single one of these instances should be running
  #it's what triggers daily backups
  cron-worker:
    image: fatfingers23/moover_cron_worker:latest
    network_mode: host
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfiles/cron-worker.Dockerfile
    env_file:
      - path: .env
        required: true

networks:
  moover_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: