// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

pub mod remove_pds;
pub mod remove_repo;
pub mod request_instance_backup;
pub mod request_pds_backup;
pub mod request_repo_backup;
pub mod sign_up_pds;