// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

pub mod describe_server;
pub mod get_repo_status;
pub mod remove_repo;
pub mod request_backup;
pub mod sign_up;